# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Green Future
email: paal.a.nordhagen@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  This is a development page for our management company Green Future AS.
  We are an alternativ investment fund that invest direct in to renewable energy
  or indirect in to technology companies based on renewable energy. Our goal is
  to be Norways best and preferable fund for exposure to renewable energy.
  The Fund will get professional investors an easy way in to the renewable sector,
  especially solar- and windenergy and disruptive technology where solar- and wind-
  energy creates business oppurtunities. We belive that the renwable sector will be
  the solution to the worlds climate challenges ahead.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://venuscurrency.com" # the base hostname & protocol for your site
twitter_username: Tull Ball
github_username:  jekyll

# Build settings
markdown: kramdown
permalink: /blog/:year/:month/:day/:title
